2024-08-28 17:43:50 | INFO | __main__ | Tested tasks:
2024-08-28 17:43:50 | INFO | __main__ | Start evaluating task pddl
Traceback (most recent call last):
  File "eval_main.py", line 238, in <module>
    main()
  File "eval_main.py", line 213, in main
    task = load_task(task_name, run_config, llm_config, agent_task_config, env_config[task_name], llm=llm, scienceworldSolver=scienceworldSolver)
  File "/home/zky/AgentBoard_metasearch/agentboard/tasks/__init__.py", line 26, in load_task
    task = registry.get_task_class(name).from_config(run_config, llm_config, agent_config, env_config, llm=llm, scienceworldSolver=scienceworldSolver)
TypeError: from_config() got an unexpected keyword argument 'scienceworldSolver'
Traceback (most recent call last):
  File "eval_main.py", line 238, in <module>
    main()
  File "eval_main.py", line 213, in main
    task = load_task(task_name, run_config, llm_config, agent_task_config, env_config[task_name], llm=llm, scienceworldSolver=scienceworldSolver)
  File "/home/zky/AgentBoard_metasearch/agentboard/tasks/__init__.py", line 26, in load_task
    task = registry.get_task_class(name).from_config(run_config, llm_config, agent_config, env_config, llm=llm, scienceworldSolver=scienceworldSolver)
TypeError: from_config() got an unexpected keyword argument 'scienceworldSolver'